# TCL File Generated by Component Editor 13.0sp1
# Tue Nov 12 15:02:12 EST 2013
# DO NOT MODIFY


# 
# st_cnt_src "st_cnt_src" v1.0
#  2013.11.12.15:02:12
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module st_cnt_src
# 
set_module_property DESCRIPTION ""
set_module_property NAME st_cnt_src
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME st_cnt_src
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL st_cnt_src
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file st_cnt_src.vhd VHDL PATH st_cnt_src.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter PKT_SIZE INTEGER 0 ""
set_parameter_property PKT_SIZE DEFAULT_VALUE 0
set_parameter_property PKT_SIZE DISPLAY_NAME PKT_SIZE
set_parameter_property PKT_SIZE WIDTH ""
set_parameter_property PKT_SIZE TYPE INTEGER
set_parameter_property PKT_SIZE UNITS None
set_parameter_property PKT_SIZE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property PKT_SIZE DESCRIPTION ""
set_parameter_property PKT_SIZE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point out0
# 
add_interface out0 avalon_streaming start
set_interface_property out0 associatedClock clock
set_interface_property out0 associatedReset reset
set_interface_property out0 dataBitsPerSymbol 8
set_interface_property out0 errorDescriptor ""
set_interface_property out0 firstSymbolInHighOrderBits true
set_interface_property out0 maxChannel 0
set_interface_property out0 readyLatency 0
set_interface_property out0 ENABLED true
set_interface_property out0 EXPORT_OF ""
set_interface_property out0 PORT_NAME_MAP ""
set_interface_property out0 SVD_ADDRESS_GROUP ""

add_interface_port out0 aso_out0_data data Output 64 
add_interface_port out0 aso_out0_ready ready Input 1
add_interface_port out0 aso_out0_valid valid Output 1
add_interface_port out0 aso_out0_sop startofpacket Output 1
add_interface_port out0 aso_out0_eop endofpacket Output 1

